### PR TITLE
Fix buffer overflows and incorrect column data type selection

### LINKED ISSUE #652: Java cli-converter fails when mvt file > 300kb
when converting single mvt tiles (>300kb) with the cli tool, following error occurs:

Failed:
java.lang.RuntimeException: java.io.IOException: Varint overflow
        at org.maplibre.mlt.converter.encodings.IntegerEncoder.lambda$encodeLong$6(IntegerEncoder.java:321)
        at org.maplibre.mlt.converter.encodings.IntegerEncoder.encodeLong(IntegerEncoder.java:325)
        at org.maplibre.mlt.converter.encodings.IntegerEncoder.encodeLongStream(IntegerEncoder.java:111)
        at org.maplibre.mlt.converter.encodings.PropertyEncoder.encodeInt64Column(PropertyEncoder.java:502)
        at org.maplibre.mlt.converter.encodings.PropertyEncoder.encodeScalarPropertyColumn(PropertyEncoder.java:244)
        at org.maplibre.mlt.converter.MltConverter.convertMvt(MltConverter.java:485)
        at org.maplibre.mlt.cli.Encode.encodeTile(Encode.java:341)
        at org.maplibre.mlt.cli.Encode.run(Encode.java:147)
        at org.maplibre.mlt.cli.Encode.main(Encode.java:82)
Caused by: java.io.IOException: Varint overflow
        at org.maplibre.mlt.converter.encodings.EncodingUtils.putVarInt(EncodingUtils.java:177)
        at org.maplibre.mlt.converter.encodings.EncodingUtils.encodeVarints(EncodingUtils.java:91)
        at org.maplibre.mlt.converter.encodings.EncodingUtils.encodeLongVarints(EncodingUtils.java:104)
        at org.maplibre.mlt.converter.encodings.IntegerEncoder.lambda$encodeLong$6(IntegerEncoder.java:319)
        ... 8 more

this is the file used to reproduce the error
[14-8802-5374.zip](https://github.com/user-attachments/files/23161280/14-8802-5374.zip)

### PR DESCRIPTION
**Pull request by TimSylvester**
Resolves #652

### CODE REVIEW

**Comment by HarelM** [comment]
Can we add a test for this use case?

**Comment by TimSylvester** [comment]
Yeah, I'm working on that.

File: java/mlt-core/src/main/java/org/maplibre/mlt/converter/encodings/EncodingUtils.java [hunk 1]
```diff
@@ -187,18 +194,26 @@ private static int putVarInt(long v, byte[] sink, int offset) throws IOException
...
   @SuppressWarnings("UnusedReturnValue")
   public static DataOutputStream putVarInt(DataOutputStream stream, long v) throws IOException {
-    final var buffer = new byte[10];
+    final var buffer = new byte[MAX_VARLONG_SIZE];
     stream.write(buffer, 0, putVarInt(v, buffer, 0));
     return stream;
   }
 
+  public static int getVarIntSize(int value) {
+    return Math.max(1, ((8 * Integer.BYTES) - Integer.numberOfLeadingZeros(value) + 6) / 7);
```
Comment (HarelM) [inline java/mlt-core/src/main/java/org/maplibre/mlt/converter/encodings/EncodingUtils.java]: Consider moving these number to be constants?

Comment (TimSylvester) [reply java/mlt-core/src/main/java/org/maplibre/mlt/converter/encodings/EncodingUtils.java]: What would you call them?  This is just for rounding.
